import ConversationManager from './ConversationManager';
import StreamingController from './StreamingController';
import { ChatMessage, AIResponse } from './types';
import Logger from '../../utils/Logger';
export interface ExecutionRequest {
requestId: string;
conversationId: string;
prompt: string;
priority: number;
timestamp: number;
}
export interface RequestCallbacks {
onStart?: (messageId: string) => void;
onChunk?: (chunk: string) => void;
onComplete?: (response: AIResponse) => void;
onError?: (error: Error) => void;
}
export class RequestManager {
private activeRequests: Map<string, ExecutionRequest> = new Map();
private requestCallbacks: Map<string, RequestCallbacks> = new Map();
/**
Dispatches an inbound conversation prompt through the local execution engine.
Maps UI callbacks directly to the streaming events generated by the runtime.
*/
public async execute(
conversationId: string,
prompt: string,
callbacks: RequestCallbacks = {},
priority = 0
): Promise<string> {
const cleanPrompt = prompt.trim();
if (!cleanPrompt) {
throw new Error('Cannot execute an empty prompt request.');
}
// 1. Queue the prompt in the ConversationManager (which updates historical state instantly)
const taskId = await ConversationManager.submitPrompt(conversationId, cleanPrompt, priority);
const request: ExecutionRequest = {
requestId: taskId,
conversationId,
prompt: cleanPrompt,
priority,
timestamp: Date.now(),
};
this.activeRequests.set(taskId, request);
this.requestCallbacks.set(taskId, callbacks);
Logger.info(Execution request mapped successfully. Request ID: ${taskId});
// 2. Bind the transactional processor to structural stream hooks if this is the first execution
this.ensureProcessorBound();
return taskId;
}
/**
Lazily binds the single-instance queue worker to run inference against the AI Provider.
*/
private ensureProcessorBound(): void {
ConversationManager.registerProcessor(async (task) => {
// Find the tracking request associated with this queue execution block
const targetRequest = Array.from(this.activeRequests.values()).find(
(req) => req.conversationId === task.conversationId && req.prompt === task.userMessage
);
if (!targetRequest) {
Logger.warn(Orphaned background generation task detected for conversation: ${task.conversationId});
return;
}
const requestId = targetRequest.requestId;
const callbacks = this.requestCallbacks.get(requestId);
// Create event listeners to catch tokens coming from the StreamingController
const handleStart = (msgId: string) => {
if (callbacks?.onStart) callbacks.onStart(msgId);
};
const handleChunk = (payload: { messageId: string; text: string }) => {
if (callbacks?.onChunk) callbacks.onChunk(payload.text);
};
const handleEnd = (payload: { messageId: string }) => {
this.cleanupRequest(requestId, handleStart, handleChunk, handleEnd, handleAbort);
};
const handleAbort = (payload: { messageId: string; reason: string }) => {
if (callbacks?.onError) {
callbacks.onError(new Error(Stream generation aborted: ${payload.reason}));
}
this.cleanupRequest(requestId, handleStart, handleChunk, handleEnd, handleAbort);
};
// Subscribe to active stream updates
StreamingController.on('stream:start', handleStart);
StreamingController.on('stream:chunk', handleChunk);
StreamingController.on('stream:end', handleEnd);
StreamingController.on('stream:abort', handleAbort);
});
}
/**
Explicitly unbinds listeners and evicts tracking entities upon stream termination.
*/
private cleanupRequest(
requestId: string,
startFn: Function,
chunkFn: Function,
endFn: Function,
abortFn: Function
): void {
StreamingController.off('stream:start', startFn as any);
StreamingController.off('stream:chunk', chunkFn as any);
StreamingController.off('stream:end', endFn as any);
StreamingController.off('stream:abort', abortFn as any);
this.activeRequests.delete(requestId);
this.requestCallbacks.delete(requestId);
Logger.debug(Request resources released safely for ID: ${requestId});
}
/**
Forces the immediate cancellation of a running request transaction.
*/
public cancelRequest(requestId: string): boolean {
const request = this.activeRequests.get(requestId);
if (!request) {
return false;
}
StreamingController.abortStream(requestId, 'User requested manual cancellation.');
this.activeRequests.delete(requestId);
this.requestCallbacks.delete(requestId);
return true;
}
/**
System health diagnostic providing total size of processing traffic.
*/
public getPendingCount(): number {
return this.activeRequests.size;
}
}
export default new RequestManager();
